// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mueazwfcbpuzqpkuiumg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11ZWF6d2ZjYnB1enFwa3VpdW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTgzODMsImV4cCI6MjA2MTIzNDM4M30.QB8xJIFnXwkkQpVvJ-YLGDsDqaZZPkgNPydjcWDWxoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);